CREATE TRIGGER AtleastOneUserType  
ON UserTypes  
FOR DELETE
AS
	DECLARE @TABLE_SIZE	INTEGER
	SET @TABLE_SIZE = (SELECT COUNT(*) FROM UserTypes)
	IF @TABLE_SIZE = 0 ROLLBACK TRANSACTION
GO

CREATE TRIGGER AtleastOneEventType  
ON UserTypes  
FOR DELETE
AS
	DECLARE @TABLE_SIZE	INTEGER
	SET @TABLE_SIZE = (SELECT COUNT(*) FROM EventTypes)
	IF @TABLE_SIZE = 0 ROLLBACK TRANSACTION
GO

CREATE TRIGGER AtleastOneBenefitType  
ON UserTypes  
FOR DELETE
AS
	DECLARE @TABLE_SIZE	INTEGER
	SET @TABLE_SIZE = (SELECT COUNT(*) FROM BenefitTypes)
	IF @TABLE_SIZE = 0 ROLLBACK TRANSACTION
GO

CREATE TRIGGER CheckStopList  
ON Registrations  
FOR INSERT, UPDATE
AS
	DECLARE @TABLE_SIZE	INTEGER
	IF EXISTS (SELECT UserAccountId, EventId FROM StopListRecords WHERE UserAccountId IN (SELECT UserAccountId FROM inserted) AND EventId IN (SELECT EventId FROM inserted))
	ROLLBACK TRANSACTION
GO
